[package]
name = "dnf5daemon"
version = "0.1.0"
edition = "2024"

[[test]]
name = "integration_test"

[dependencies]
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["macros"] }
zbus = { version = "5.12.0", features = ["tokio"] }
