[package]
name = "dnf1"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.228"
serde_repr = "0.1.20"
tokio = { version = "1.48.0", features = ["macros"] }
zbus = { version = "5.12.0", features = ["tokio"] }
